<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21786" started-at="2019-01-30T04:20:54Z" finished-at="2019-01-30T04:21:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21786" started-at="2019-01-30T04:20:54Z" finished-at="2019-01-30T04:21:16Z">
      <class name="com.sample.SignUpTest">
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.sample.SignUpTest@5f2108b5]" name="Setup" is-config="true" duration-ms="5453" started-at="2019-01-30T04:20:54Z" finished-at="2019-01-30T04:21:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="ResetApp()[pri:0, instance:com.sample.SignUpTest@5f2108b5]" name="ResetApp" is-config="true" duration-ms="2627" started-at="2019-01-30T04:21:00Z" finished-at="2019-01-30T04:21:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ResetApp -->
        <test-method status="FAIL" signature="SignUp()[pri:0, instance:com.sample.SignUpTest@5f2108b5]" name="SignUp" duration-ms="13673" started-at="2019-01-30T04:21:03Z" finished-at="2019-01-30T04:21:16Z">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Server returned HTTP response code: 500 for URL: http://172.30.13.118:8090/utility/v2/otp/to/639897654321/template/110]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Server returned HTTP response code: 500 for URL: http://172.30.13.118:8090/utility/v2/otp/to/639897654321/template/110
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
at java.security.AccessController.doPrivileged(Native Method)
at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at com.sample.SignUpTest.SignUp(SignUpTest.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://172.30.13.118:8090/utility/v2/otp/to/639897654321/template/110
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
at com.sample.SignUpTest.SignUp(SignUpTest.java:73)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp -->
      </class> <!-- com.sample.SignUpTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
